stock_general_info_file_name = 'stock_general_info.csv'
etf_general_info_file_name = 'etf_general_info.csv'

trading_book_name = 'trading book.xlsm'


col_stock_id = u'股票代码'
col_stock_name = u'股票名称'
col_etf_id = u'基金代码'
col_etf_name = u'基金简称'
col_position = u'持仓'
col_position_available = u'可用'
col_market_value = u'市值'
col_current_price = u'现价'
col_cost = u'成本'
col_profit = u'浮动盈亏'
col_profit_rate = u'盈亏(%)'
col_date = u'日期'
col_open = u'开盘'
col_close = u'收盘'
col_high = u'最高'
col_low = u'最低'
col_buy_count = u'买入数量'
col_buying_price = u'买入价格'
col_support = u'支撑'
col_resistance = u'阻力'
col_adjusted_stoploss = u'调整后/移动止损价格'
col_adjusted_take_profit = u'调整后止盈价格'
col_stoploss_percent = u'止损(%)'
col_take_profit_percent = u'止盈(%)'
col_profit_stoploss_rate = u'盈亏比'
col_time = u'时间'
col_buy_amount = u'买入金额'
