COL_STOCK_ID = "股票代码"
COL_STOCK_NAME = "股票名称"
COL_ETF_ID = "基金代码"
COL_ETF_NAME = "基金简称"
COL_POSITION = "持仓"
COL_POSITION_AVAILABLE = "可用"
COL_MARKET_VALUE = "市值"
COL_CURRENT_PRICE = "现价"
COL_COST = "成本"
COL_PROFIT = "浮动盈亏"
COL_PROFIT_RATE = "盈亏(%)"
COL_DATE = "日期"
COL_OPEN = "开盘"
COL_CLOSE = "收盘"
COL_HIGH = "最高"
COL_LOW = "最低"
COL_VOLUME = "成交量"
COL_BUY_COUNT = "买入数量"
COL_BUYING_PRICE = "买入价格"
COL_SUPPORT = "支撑"
COL_RESISTANCE = "阻力"
COL_ADJUSTED_STOPLOSS = "调整后/移动止损价格"
COL_ADJUSTED_TAKE_PROFIT = "调整后止盈价格"
COL_STOPLOSS_PERCENT = "止损(%)"
COL_TAKE_PROFIT_PERCENT = "止盈(%)"
COL_PROFIT_STOPLOSS_RATE = "盈亏比"
COL_TIME = "时间"
COL_BUY_AMOUNT = "买入金额"
COL_IPO_DATE = "上市日期"
COL_DELISTING_DATE = "退市日期"

COL_MONITOR_PRICE = "监控价格"
COL_COMMENT = "comment"
# platforms to be notified
COL_EMAIL = "email"
COL_MOBILE = "mobile"
COL_PC = "pc"


# database
DATABASE_NAME = "frog.db"
