"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { ErrorBanner } from "@/components/error-banner";
import { createMonitorTarget, deleteMonitorTarget, listMonitorTargets, setMonitorTargetEnabled, updateMonitorTarget } from "@/lib/api-client";
import type { CreateMonitorTargetInput, ListMonitorTargetsParams, MonitorCondition, MonitorTarget } from "@/lib/types";
import { MonitorTargetFormModal } from "./monitor-target-form-modal";
import { MonitorTargetTable } from "./monitor-target-table";

export function MonitorPage() {
  const [targets, setTargets] = useState<MonitorTarget[]>([]); const [filters, setFilters] = useState<ListMonitorTargetsParams>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<MonitorTarget | null | undefined>(undefined); const [busyActions, setBusyActions] = useState<Set<string>>(new Set()); const requestId = useRef(0);
  const load = useCallback(async (nextFilters = filters) => { const id = ++requestId.current; setLoading(true); try { const next = await listMonitorTargets(nextFilters); if (id === requestId.current) { setTargets(next); setError(null); } } catch (err) { if (id === requestId.current) setError(err instanceof Error ? err.message : "Failed to load monitor targets"); } finally { if (id === requestId.current) setLoading(false); } }, [filters]);
  useEffect(() => { void load(filters); }, [filters, load]);
  function setFilter<K extends keyof ListMonitorTargetsParams>(key: K, value: ListMonitorTargetsParams[K] | undefined) { setFilters((current) => ({ ...current, [key]: value })); }
  function setActionBusy(key: string, busy: boolean) { setBusyActions((current) => { const next = new Set(current); if (busy) next.add(key); else next.delete(key); return next; }); }
  async function save(input: CreateMonitorTargetInput) { const actionKey = editing ? `${editing.id}:edit` : null; if (actionKey) setActionBusy(actionKey, true); try { if (editing) await updateMonitorTarget(editing.id, input); else await createMonitorTarget(input); setEditing(undefined); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to save monitor target"); throw err; } finally { if (actionKey) setActionBusy(actionKey, false); } }
  async function toggle(target: MonitorTarget) { const actionKey = `${target.id}:toggle`; setActionBusy(actionKey, true); setError(null); try { await setMonitorTargetEnabled(target.id, !target.enabled); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to update monitor target"); } finally { setActionBusy(actionKey, false); } }
  async function remove(target: MonitorTarget) { if (!window.confirm(`Permanently delete monitor target ${target.stock_code}?`)) return; const actionKey = `${target.id}:delete`; setActionBusy(actionKey, true); setError(null); try { await deleteMonitorTarget(target.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to delete monitor target"); } finally { setActionBusy(actionKey, false); } }
  return <section className="page monitor-page"><div className="page__header"><div><p className="monitor-eyebrow">Shared manual targets</p><h1>Monitor console</h1><p className="muted">Maintain the shared target list used for manual market monitoring.</p></div><div className="actions"><button className="button button--secondary" type="button" onClick={() => void load()}>Refresh targets</button><button className="button" type="button" onClick={() => setEditing(null)}>Create target</button></div></div><section className="panel"><div className="monitor-filter-bar" aria-label="Monitor target filters"><label>Market<select aria-label="Market filter" value={filters.market ?? ""} onChange={(event) => setFilter("market", (event.target.value || undefined) as "A" | "HK" | "ETF" | undefined)}><option value="">All markets</option><option value="A">A-share</option><option value="HK">Hong Kong</option><option value="ETF">ETF</option></select></label><label>Frequency<select aria-label="Frequency filter" value={filters.frequency ?? ""} onChange={(event) => setFilter("frequency", (event.target.value || undefined) as "daily" | "intraday" | undefined)}><option value="">All frequencies</option><option value="daily">Daily</option><option value="intraday">Intraday</option></select></label><label>Status<select aria-label="Status filter" value={filters.enabled === undefined ? "" : String(filters.enabled)} onChange={(event) => setFilter("enabled", event.target.value === "" ? undefined : event.target.value === "true")}><option value="">All statuses</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label>Condition<select aria-label="Condition filter" value={filters.condition_type ?? ""} onChange={(event) => setFilter("condition_type", (event.target.value || undefined) as MonitorCondition["type"] | undefined)}><option value="">All conditions</option><option value="price_threshold">Price threshold</option><option value="ma_cross">MA cross</option><option value="close_cross_ma">Close crosses MA</option><option value="rsi">RSI</option></select></label></div>{error ? <ErrorBanner message={error} /> : null}{loading ? <p className="monitor-loading" role="status">Loading monitor targets…</p> : <MonitorTargetTable busyActions={busyActions} onDelete={(target) => void remove(target)} onEdit={setEditing} onToggle={(target) => void toggle(target)} targets={targets} />}</section><MonitorTargetFormModal open={editing !== undefined} target={editing ?? null} onClose={() => setEditing(undefined)} onSubmit={save} /></section>;
}
