"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { ErrorBanner } from "@/components/error-banner";
import { createMonitorTarget, deleteMonitorTarget, getMonitorTargetHealth, listMonitorTargets, setMonitorTargetEnabled, updateMonitorTarget } from "@/lib/api-client";
import type { CreateMonitorTargetInput, ListMonitorTargetsParams, MonitorCondition, MonitorTarget, MonitorTargetHealth } from "@/lib/types";
import { MonitorHealthPanel } from "./monitor-health-panel";
import { MonitorTargetFormModal } from "./monitor-target-form-modal";
import { MonitorTargetTable } from "./monitor-target-table";
import { TargetOperationGuard } from "./target-operation-guard";

export function MonitorPage() {
  const [targets, setTargets] = useState<MonitorTarget[]>([]); const [health, setHealth] = useState<MonitorTargetHealth | null>(null); const [filters, setFilters] = useState<ListMonitorTargetsParams>({}); const [loading, setLoading] = useState(true); const [healthLoading, setHealthLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [healthError, setHealthError] = useState<string | null>(null); const [editing, setEditing] = useState<MonitorTarget | null | undefined>(undefined); const [busyTargetIds, setBusyTargetIds] = useState<Set<number>>(new Set()); const targetOperations = useRef(new TargetOperationGuard()); const manualRequestId = useRef(0); const healthRequestId = useRef(0);
  const loadManualTargets = useCallback(async (nextFilters = filters) => { const id = ++manualRequestId.current; setLoading(true); try { const next = await listMonitorTargets(nextFilters); if (id === manualRequestId.current) { setTargets(next); setError(null); } } catch (err) { if (id === manualRequestId.current) setError(err instanceof Error ? err.message : "Failed to load monitor targets"); } finally { if (id === manualRequestId.current) setLoading(false); } }, [filters]);
  const loadHealth = useCallback(async () => { const id = ++healthRequestId.current; setHealthLoading(true); try { const next = await getMonitorTargetHealth(); if (id === healthRequestId.current) { setHealth(next); setHealthError(null); } } catch (err) { if (id === healthRequestId.current) setHealthError(err instanceof Error ? err.message : "Failed to load operational health"); } finally { if (id === healthRequestId.current) setHealthLoading(false); } }, []);
  const refreshAll = useCallback(async () => { await Promise.allSettled([loadManualTargets(), loadHealth()]); }, [loadHealth, loadManualTargets]);
  useEffect(() => { void loadManualTargets(filters); }, [filters, loadManualTargets]);
  useEffect(() => { void loadHealth(); }, [loadHealth]);
  function setFilter<K extends keyof ListMonitorTargetsParams>(key: K, value: ListMonitorTargetsParams[K] | undefined) { setFilters((current) => ({ ...current, [key]: value })); }
  function beginTargetOperation(targetId: number) { if (!targetOperations.current.begin(targetId)) return false; setBusyTargetIds((current) => new Set(current).add(targetId)); return true; }
  function finishTargetOperation(targetId: number) { targetOperations.current.finish(targetId); setBusyTargetIds((current) => { const next = new Set(current); next.delete(targetId); return next; }); }
  async function save(input: CreateMonitorTargetInput) { const targetId = editing?.id; if (targetId !== undefined && !beginTargetOperation(targetId)) return; try { if (editing) await updateMonitorTarget(editing.id, input); else await createMonitorTarget(input); setEditing(undefined); await refreshAll(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to save monitor target"); throw err; } finally { if (targetId !== undefined) finishTargetOperation(targetId); } }
  async function toggle(target: MonitorTarget) { if (!beginTargetOperation(target.id)) return; setError(null); try { await setMonitorTargetEnabled(target.id, !target.enabled); await refreshAll(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to update monitor target"); } finally { finishTargetOperation(target.id); } }
  async function remove(target: MonitorTarget) { if (!window.confirm(`Permanently delete monitor target ${target.stock_code}?`) || !beginTargetOperation(target.id)) return; setError(null); try { await deleteMonitorTarget(target.id); await refreshAll(); } catch (err) { setError(err instanceof Error ? err.message : "Failed to delete monitor target"); } finally { finishTargetOperation(target.id); } }
  return <section className="page monitor-page"><div className="page__header"><div><p className="monitor-eyebrow">Shared manual targets</p><h1>Monitor console</h1><p className="muted">Maintain the shared target list used for manual market monitoring.</p></div><div className="actions"><button className="button button--secondary" type="button" onClick={() => void refreshAll()}>Refresh targets</button><button className="button" type="button" onClick={() => setEditing(null)}>Create target</button></div></div><MonitorHealthPanel error={healthError} health={health} loading={healthLoading} />{error ? <ErrorBanner message={error} /> : null}<section className="panel"><div className="monitor-filter-bar" aria-label="Monitor target filters"><label>Market<select aria-label="Market filter" value={filters.market ?? ""} onChange={(event) => setFilter("market", (event.target.value || undefined) as "A" | "HK" | "ETF" | undefined)}><option value="">All markets</option><option value="A">A-share</option><option value="HK">Hong Kong</option><option value="ETF">ETF</option></select></label><label>Frequency<select aria-label="Frequency filter" value={filters.frequency ?? ""} onChange={(event) => setFilter("frequency", (event.target.value || undefined) as "daily" | "intraday" | undefined)}><option value="">All frequencies</option><option value="daily">Daily</option><option value="intraday">Intraday</option></select></label><label>Status<select aria-label="Status filter" value={filters.enabled === undefined ? "" : String(filters.enabled)} onChange={(event) => setFilter("enabled", event.target.value === "" ? undefined : event.target.value === "true")}><option value="">All statuses</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label>Condition<select aria-label="Condition filter" value={filters.condition_type ?? ""} onChange={(event) => setFilter("condition_type", (event.target.value || undefined) as MonitorCondition["type"] | undefined)}><option value="">All conditions</option><option value="price_threshold">Price threshold</option><option value="ma_cross">MA cross</option><option value="close_cross_ma">Close crosses MA</option><option value="rsi">RSI</option></select></label></div>{loading ? <p className="monitor-loading">Loading manual targets…</p> : <MonitorTargetTable targets={targets} busyTargetIds={busyTargetIds} onEdit={setEditing} onToggle={(target) => void toggle(target)} onDelete={(target) => void remove(target)} />}</section><MonitorTargetFormModal open={editing !== undefined} target={editing ?? null} onClose={() => setEditing(undefined)} onSubmit={save} /></section>;
}
