"use client";

import { useEffect, useState } from "react";
import type { CreateMonitorTargetInput, MonitorCondition, MonitorTarget } from "@/lib/types";
import { ConditionEditor } from "./condition-editor";

type Props = { open: boolean; target: MonitorTarget | null; onClose: () => void; onSubmit: (input: CreateMonitorTargetInput) => Promise<void> | void };
const defaultCondition: MonitorCondition = { type: "price_threshold", direction: "above", value: 0 };

export function MonitorTargetFormModal({ open, target, onClose, onSubmit }: Props) {
  const [stockCode, setStockCode] = useState(""); const [market, setMarket] = useState<CreateMonitorTargetInput["market"]>("A"); const [frequency, setFrequency] = useState<"daily" | "intraday">("daily"); const [resetMode, setResetMode] = useState<"auto" | "manual">("auto"); const [enabled, setEnabled] = useState(true); const [note, setNote] = useState(""); const [condition, setCondition] = useState<MonitorCondition>(defaultCondition); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setStockCode(target?.stock_code ?? ""); setMarket(target?.market ?? "A"); setFrequency(target?.frequency ?? "daily"); setResetMode(target?.reset_mode ?? "auto"); setEnabled(target?.enabled ?? true); setNote(target?.note ?? ""); setCondition(target?.condition ?? defaultCondition); setError(null); setSaving(false); } }, [open, target]);
  if (!open) return null;
  async function submit(event: React.FormEvent) { event.preventDefault(); if (condition.type === "close_cross_ma" && (market !== "A" || frequency !== "daily")) { setError("Close crosses MA is available for daily A-share targets only"); return; } setSaving(true); setError(null); try { await onSubmit({ stock_code: stockCode.trim(), market, frequency, reset_mode: resetMode, enabled, note: note.trim() || null, condition }); } catch (err) { setError(err instanceof Error ? err.message : "Failed to save monitor target"); } finally { setSaving(false); } }
  return <div className="modal-backdrop" onClick={onClose}><div className="modal monitor-modal" role="dialog" aria-modal="true" aria-label={target ? "Edit monitor target" : "Create monitor target"} onClick={(event) => event.stopPropagation()}><div className="modal__header"><h2>{target ? "Edit monitor target" : "Create monitor target"}</h2></div><form onSubmit={submit}><div className="modal__body form"><label>Stock code<input aria-label="Stock code" required value={stockCode} onChange={(event) => setStockCode(event.target.value)} /></label><div className="monitor-form-grid"><label>Market<select aria-label="Market" value={market} onChange={(event) => setMarket(event.target.value as CreateMonitorTargetInput["market"])}><option value="A">A-share</option><option value="HK">Hong Kong</option><option value="ETF">ETF</option></select></label><label>Frequency<select aria-label="Frequency" value={frequency} onChange={(event) => setFrequency(event.target.value as "daily" | "intraday")}><option value="daily">Daily</option><option value="intraday">Intraday</option></select></label></div><ConditionEditor condition={condition} market={market} frequency={frequency} onChange={setCondition} /><label>Note<input aria-label="Note" value={note} onChange={(event) => setNote(event.target.value)} /></label><div className="monitor-form-grid"><label>Reset mode<select aria-label="Reset mode" value={resetMode} onChange={(event) => setResetMode(event.target.value as "auto" | "manual")}><option value="auto">Automatic</option><option value="manual">Manual</option></select></label><label className="monitor-enabled"><input aria-label="Enabled" type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> Enabled</label></div>{error ? <div className="error-banner" role="alert">{error}</div> : null}</div><div className="modal__footer"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button" disabled={saving} type="submit">{saving ? "Saving…" : target ? "Save changes" : "Create target"}</button></div></form></div></div>;
}
