import { DataTable, type Column } from "@/components/data-table";
import type { MonitorTarget } from "@/lib/types";

const describeCondition = (target: MonitorTarget) => `${target.condition.type.replaceAll("_", " ")} · ${target.condition.direction}`;
export function MonitorTargetTable({ targets, busyId, onEdit, onToggle, onDelete }: { targets: MonitorTarget[]; busyId: number | null; onEdit: (target: MonitorTarget) => void; onToggle: (target: MonitorTarget) => void; onDelete: (target: MonitorTarget) => void }) {
  const columns: Column<MonitorTarget>[] = [{ key: "stock", header: "Target", render: (target) => <strong>{target.stock_code}</strong>, sortable: (target) => target.stock_code }, { key: "scope", header: "Scope", render: (target) => `${target.market} · ${target.frequency}` }, { key: "condition", header: "Condition", render: describeCondition }, { key: "status", header: "Status", render: (target) => <span className={`status-badge ${target.enabled ? "status-badge--active" : ""}`}>{target.enabled ? "Enabled" : "Disabled"}</span> }, { key: "note", header: "Note", render: (target) => target.note || <span className="muted">—</span> }, { key: "actions", header: "Actions", render: (target) => <div className="actions monitor-actions"><button className="button button--secondary" type="button" onClick={() => onEdit(target)}>Edit</button><button aria-label={`${target.enabled ? "Disable" : "Enable"} ${target.stock_code}`} className="button button--secondary" disabled={busyId === target.id} type="button" onClick={() => onToggle(target)}>{target.enabled ? "Disable" : "Enable"}</button><button aria-label={`Delete ${target.stock_code}`} className="button button--secondary monitor-delete" disabled={busyId === target.id} type="button" onClick={() => onDelete(target)}>Delete</button></div> }];
  return <MonitorTargetDataTable columns={columns} targets={targets} />;
}
function MonitorTargetDataTable({ columns, targets }: { columns: Column<MonitorTarget>[]; targets: MonitorTarget[] }) { return <DataTable columns={columns} density="compact" emptyTitle="No manual monitor targets yet" getRowKey={(target) => target.id} rows={targets} />; }
