# ruff: noqa: E501

from __future__ import annotations

import os
import uuid
from datetime import date
from unittest.mock import Mock

import pytest
from sqlalchemy import create_engine, event, text
from sqlalchemy.engine import Connection, Engine

import storage.storage_db as storage_db_module
from paper_trading.storage.enum_migration import PAPER_TRADING_ENUM_GROUPS
from paper_trading.storage.matching_status_migration import (
    MatchingStatusEnumMigrationError,
    bootstrap_paper_matching_run_status,
    migrate_paper_matching_status_enum,
)
from storage.config import StorageConfig
from storage.storage_db import StorageDb, reset_storage

LABELS = ("running", "completed", "completed_with_warnings", "failed")
EXPECTED_TYPE_NAMES = sorted(group.type_name for group in PAPER_TRADING_ENUM_GROUPS)


def test_sqlite_dry_run_does_not_execute_postgresql_ddl():
    engine = create_engine("sqlite://")
    with engine.begin() as connection:
        result = migrate_paper_matching_status_enum(connection, dry_run=True)

    assert result.dry_run is True
    assert result.labels == LABELS
    assert result.converted is False
    assert result.index_verified is False


def postgres_engine() -> Engine:
    url = os.getenv("TEST_POSTGRESQL_URL")
    if not url:
        pytest.skip("TEST_POSTGRESQL_URL is unavailable")
    assert url is not None
    return create_engine(url)


@pytest.fixture()
def postgres_schema():
    engine = postgres_engine()
    schema = f"matching_status_migration_{uuid.uuid4().hex}"
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        connection.execute(text(f'SET search_path TO "{schema}"'))
        _create_legacy_schema(connection)
    yield engine, schema
    with engine.begin() as connection:
        connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
    engine.dispose()


@pytest.fixture()
def empty_postgres_schema():
    engine = postgres_engine()
    schema = f"matching_status_bootstrap_{uuid.uuid4().hex}"
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
    yield engine, schema
    with engine.begin() as connection:
        connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
    engine.dispose()


@pytest.fixture()
def matching_only_postgres_schema():
    engine = postgres_engine()
    schema = f"matching_status_only_{uuid.uuid4().hex}"
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        connection.execute(text(f'SET search_path TO "{schema}"'))
        connection.execute(
            text(
                "CREATE TABLE paper_matching_runs ("
                "id integer generated by default as identity primary key, "
                "trade_date date NOT NULL, scope_key varchar(40) NOT NULL, status varchar(32) NOT NULL)"
            )
        )
        connection.execute(
            text(
                "CREATE UNIQUE INDEX uq_matching_active_scope "
                "ON paper_matching_runs (trade_date, scope_key) WHERE status = 'running'"
            )
        )
    yield engine, schema
    with engine.begin() as connection:
        connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
    engine.dispose()


def _connection(engine: Engine, schema: str) -> Connection:
    connection = engine.connect()
    connection.execute(text(f'SET search_path TO "{schema}"'))
    return connection


def _create_legacy_schema(connection: Connection) -> None:
    statements = (
        "CREATE TABLE paper_accounts (id integer generated by default as identity primary key, status varchar(20) NOT NULL DEFAULT 'active', fee_preset varchar(30) NOT NULL DEFAULT 'a_share')",
        "CREATE TABLE paper_cash_ledger (id integer primary key, event_type varchar(20) NOT NULL)",
        "CREATE TABLE paper_positions (id integer primary key, source varchar(20) NOT NULL DEFAULT 'trade', market varchar(20) NOT NULL DEFAULT 'a_share')",
        "CREATE TABLE paper_position_lots (id integer primary key, source varchar(20) NOT NULL DEFAULT 'trade', market varchar(20) NOT NULL DEFAULT 'a_share')",
        "CREATE TABLE paper_orders (id integer generated by default as identity primary key, account_id integer, side varchar(10) NOT NULL, status varchar(30) NOT NULL, validity_status varchar(20), market varchar(20) NOT NULL DEFAULT 'a_share', idempotency_key varchar(100))",
        "CREATE TABLE paper_trades (id integer primary key, side varchar(10) NOT NULL, market varchar(20) NOT NULL DEFAULT 'a_share')",
        "CREATE TABLE paper_position_round_trips (id integer primary key, status varchar(20) NOT NULL DEFAULT 'open')",
        "CREATE TABLE paper_trade_validity_checks (id integer primary key, side varchar(10) NOT NULL, status varchar(20) NOT NULL, data_granularity varchar(20) NOT NULL DEFAULT 'daily', market varchar(20) NOT NULL DEFAULT 'a_share')",
        "CREATE TABLE paper_pending_settlement (id integer primary key, source varchar(20) NOT NULL)",
        "CREATE TABLE paper_ledger_rebuilds (id integer primary key, status varchar(20) NOT NULL)",
        "CREATE TABLE paper_matching_runs (id integer generated by default as identity primary key, trade_date date NOT NULL, scope_key varchar(40) NOT NULL, status varchar(32) NOT NULL)",
        "CREATE INDEX ix_paper_positions_market ON paper_positions (market)",
        "CREATE INDEX ix_paper_position_lots_market ON paper_position_lots (market)",
        "CREATE INDEX ix_paper_orders_status ON paper_orders (status)",
        "CREATE INDEX ix_paper_orders_validity_status ON paper_orders (validity_status)",
        "CREATE INDEX ix_paper_orders_market ON paper_orders (market)",
        "CREATE INDEX ix_paper_trades_market ON paper_trades (market)",
        "CREATE INDEX ix_paper_trade_validity_checks_status ON paper_trade_validity_checks (status)",
        "CREATE INDEX ix_paper_trade_validity_checks_market ON paper_trade_validity_checks (market)",
        "CREATE INDEX ix_paper_position_round_trips_status ON paper_position_round_trips (status)",
        "CREATE INDEX ix_paper_ledger_rebuilds_status ON paper_ledger_rebuilds (status)",
        "CREATE UNIQUE INDEX uq_matching_active_scope ON paper_matching_runs (trade_date, scope_key) WHERE status = 'running'",
    )
    for statement in statements:
        connection.execute(text(statement))


def test_postgresql_bootstrap_dry_run_reports_missing_table_without_ddl(empty_postgres_schema):
    engine, schema = empty_postgres_schema
    with _connection(engine, schema) as connection:
        result = bootstrap_paper_matching_run_status(connection, dry_run=True)

        assert result.table_exists is False
        assert result.table_created is False
        assert result.status_column_type is None
        assert result.labels == LABELS
        assert result.observed_legacy_values == ()
        assert result.index_verified is False
        assert connection.execute(text("SELECT to_regclass('paper_matching_runs')")).scalar_one() is None


def test_postgresql_bootstrap_creates_fresh_enum_table_and_index(empty_postgres_schema):
    engine, schema = empty_postgres_schema
    with _connection(engine, schema) as connection:
        result = bootstrap_paper_matching_run_status(connection)

        assert result.table_exists is False
        assert result.table_created is True
        assert result.status_column_type == "paper_matching_run_status"
        assert result.converted is False
        assert result.labels == LABELS
        assert result.observed_legacy_values == ()
        assert result.index_verified is True
        assert (
            connection.execute(text("SELECT to_regclass('paper_matching_runs')")).scalar_one() == "paper_matching_runs"
        )
        assert connection.execute(text("SELECT to_regclass('paper_account_snapshots')")).scalar_one() is None
        assert connection.execute(text("SELECT to_regclass('paper_valuation_gaps')")).scalar_one() is None
        enum_names = (
            connection.execute(
                text(
                    "SELECT t.typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
                    "WHERE n.nspname = current_schema() AND t.typtype = 'e' ORDER BY t.typname"
                )
            )
            .scalars()
            .all()
        )
        assert enum_names == ["paper_matching_run_status"]


def test_postgresql_bootstrap_reports_legacy_values_and_is_idempotent(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        for status in ("completed", "running"):
            connection.execute(
                text("INSERT INTO paper_matching_runs (trade_date, scope_key, status) VALUES (:date, :scope, :status)"),
                {"date": date(2026, 7, 31), "scope": status, "status": status},
            )

        dry_run = bootstrap_paper_matching_run_status(connection, dry_run=True)
        first = bootstrap_paper_matching_run_status(connection)
        second = bootstrap_paper_matching_run_status(connection)

    assert dry_run.table_exists is True
    assert dry_run.table_created is False
    assert dry_run.status_column_type == "character varying(32)"
    assert dry_run.converted is True
    assert dry_run.observed_legacy_values == ("completed", "running")
    assert first.converted is True
    assert second.table_created is False
    assert second.converted is False


def test_postgresql_storage_startup_preserves_governed_paper_storage_boundary(postgres_schema, monkeypatch):
    engine, schema = postgres_schema
    startup_engine = create_engine(engine.url)

    @event.listens_for(startup_engine, "connect")
    def set_search_path(dbapi_connection, connection_record):
        with dbapi_connection.cursor() as cursor:
            cursor.execute(f'SET search_path TO "{schema}"')

    config = Mock(spec=StorageConfig)
    config.get_db_host.return_value = "localhost"
    config.get_db_port.return_value = 5432
    config.get_db_name.return_value = "test_db"
    config.get_db_username.return_value = "test_user"
    config.get_db_password.return_value = "test_pass"
    monkeypatch.setattr("storage.storage_db.create_engine", lambda *args, **kwargs: startup_engine)
    monkeypatch.setattr(StorageDb, "ensure_a_stock_basic_schema", Mock())
    monkeypatch.setattr(StorageDb, "ensure_blackroom_records_table", Mock())
    monkeypatch.setattr(StorageDb, "ensure_paper_trading_schema", Mock())

    try:
        reset_storage()
        StorageDb(config)
        with _connection(engine, schema) as connection:
            enum_names = (
                connection.execute(
                    text(
                        "SELECT t.typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
                        "WHERE n.nspname = current_schema() AND t.typtype = 'e'"
                    )
                )
                .scalars()
                .all()
            )
            column_types = {
                (column.table_name, column.column_name): connection.execute(
                    text(
                        "SELECT lower(format_type(a.atttypid, a.atttypmod)) FROM pg_attribute a "
                        "JOIN pg_class c ON c.oid = a.attrelid "
                        "JOIN pg_namespace n ON n.oid = c.relnamespace "
                        "WHERE n.nspname = current_schema() AND c.relname = :table_name "
                        "AND a.attname = :column_name"
                    ),
                    {"table_name": column.table_name, "column_name": column.column_name},
                ).scalar_one()
                for group in PAPER_TRADING_ENUM_GROUPS
                for column in group.columns
            }
            paper_account_snapshots = connection.execute(
                text("SELECT to_regclass('paper_account_snapshots')")
            ).scalar_one()
            paper_valuation_gaps = connection.execute(text("SELECT to_regclass('paper_valuation_gaps')")).scalar_one()
            daily_bar_diagnostics = connection.execute(text("SELECT to_regclass('daily_bar_diagnostics')")).scalar_one()
            stock_monitor_targets = connection.execute(text("SELECT to_regclass('stock_monitor_targets')")).scalar_one()
            forecast_ssf_candidates = connection.execute(
                text("SELECT to_regclass('forecast_ssf_candidates')")
            ).scalar_one()
    finally:
        reset_storage()
        storage_db_module._metadata_initialized_pids.discard(os.getpid())
        startup_engine.dispose()

    assert enum_names == []
    assert all(column_type.startswith("character varying") for column_type in column_types.values())
    assert paper_account_snapshots is None
    assert paper_valuation_gaps is None
    assert daily_bar_diagnostics is None
    assert stock_monitor_targets is None
    assert forecast_ssf_candidates is None


def test_postgresql_rejects_unknown_legacy_status_without_changes(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(
            text("INSERT INTO paper_matching_runs (trade_date, scope_key, status) VALUES (:date, 'all', 'unknown')"),
            {"date": date(2026, 7, 31)},
        )
        with pytest.raises(MatchingStatusEnumMigrationError):
            migrate_paper_matching_status_enum(connection)
        assert connection.execute(text("SELECT status FROM paper_matching_runs")).scalar_one() == "unknown"


def test_postgresql_wrapper_converts_matching_run_without_other_governed_tables(matching_only_postgres_schema):
    engine, schema = matching_only_postgres_schema
    with _connection(engine, schema) as connection:
        result = migrate_paper_matching_status_enum(connection)

        assert result.converted is True
        assert result.labels == LABELS
        assert result.index_verified is True
        assert _status_column_type_for_schema(connection, schema) == "paper_matching_run_status"
        assert connection.execute(text("SELECT to_regclass('paper_orders')")).scalar_one() is None


def _status_column_type_for_schema(connection: Connection, schema: str) -> str:
    return str(
        connection.execute(
            text(
                "SELECT format_type(a.atttypid, a.atttypmod) FROM pg_attribute a "
                "JOIN pg_class c ON c.oid = a.attrelid "
                "JOIN pg_namespace n ON n.oid = c.relnamespace "
                "WHERE n.nspname = :schema AND c.relname = 'paper_matching_runs' "
                "AND a.attname = 'status'"
            ),
            {"schema": schema},
        ).scalar_one()
    )


def test_postgresql_converts_labels_and_verifies_active_partial_index(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        for status in LABELS:
            connection.execute(
                text("INSERT INTO paper_matching_runs (trade_date, scope_key, status) VALUES (:date, :scope, :status)"),
                {"date": date(2026, 7, 31), "scope": status, "status": status},
            )
        result = migrate_paper_matching_status_enum(connection)

        assert result.converted is True
        assert result.labels == LABELS
        assert result.index_verified is True
        assert (
            connection.execute(
                text(
                    "SELECT t.typname FROM pg_type t "
                    "JOIN pg_namespace n ON n.oid = t.typnamespace "
                    "WHERE n.nspname = :schema AND t.typname = 'paper_matching_run_status'"
                ),
                {"schema": schema},
            ).scalar_one()
            == "paper_matching_run_status"
        )
        assert connection.execute(
            text(
                "SELECT enumlabel FROM pg_enum "
                "JOIN pg_type ON pg_type.oid = pg_enum.enumtypid "
                "JOIN pg_namespace ON pg_namespace.oid = pg_type.typnamespace "
                "WHERE pg_namespace.nspname = :schema "
                "AND pg_type.typname = 'paper_matching_run_status' ORDER BY enumsortorder"
            ),
            {"schema": schema},
        ).all() == [(label,) for label in LABELS]
        assert (
            connection.execute(
                text(
                    "SELECT pg_get_expr(indpred, indrelid) FROM pg_index "
                    "JOIN pg_class ON pg_class.oid = pg_index.indexrelid "
                    "JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace "
                    "WHERE pg_namespace.nspname = :schema "
                    "AND pg_class.relname = 'uq_matching_active_scope'"
                ),
                {"schema": schema},
            )
            .scalar_one()
            .lower()
            .find("running")
            >= 0
        )
        assert (
            connection.execute(
                text(
                    "SELECT pg_get_expr(indpred, indrelid) FROM pg_index "
                    "JOIN pg_class ON pg_class.oid = pg_index.indexrelid "
                    "JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace "
                    "WHERE pg_namespace.nspname = :schema "
                    "AND pg_class.relname = 'uq_matching_active_scope'"
                ),
                {"schema": schema},
            )
            .scalar_one()
            .lower()
            .find("paper_matching_run_status")
            >= 0
        )


def test_postgresql_migration_is_idempotent(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        first = migrate_paper_matching_status_enum(connection)
        second = migrate_paper_matching_status_enum(connection)

    assert first.converted is True
    assert second.converted is False
    assert second.labels == LABELS
    assert second.index_verified is True


def test_postgresql_reuses_existing_enum_when_converting_legacy_column(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(
            text(
                "CREATE TYPE paper_matching_run_status AS ENUM "
                "('running', 'completed', 'completed_with_warnings', 'failed')"
            )
        )

        result = migrate_paper_matching_status_enum(connection)

        assert result.converted is True
        assert (
            connection.execute(
                text(
                    "SELECT format_type(a.atttypid, a.atttypmod) FROM pg_attribute a "
                    "JOIN pg_class c ON c.oid = a.attrelid "
                    "JOIN pg_namespace n ON n.oid = c.relnamespace "
                    "WHERE n.nspname = :schema AND c.relname = 'paper_matching_runs' "
                    "AND a.attname = 'status'"
                ),
                {"schema": schema},
            ).scalar_one()
            == "paper_matching_run_status"
        )


def test_postgresql_dry_run_reports_preflight_facts_without_ddl(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        result = migrate_paper_matching_status_enum(connection, dry_run=True)

        assert result.dry_run is True
        assert result.converted is True
        assert result.labels == LABELS
        assert result.index_verified is True
        assert (
            connection.execute(
                text(
                    "SELECT EXISTS ("
                    "SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
                    "WHERE n.nspname = :schema AND t.typname = 'paper_matching_run_status'"
                    ")"
                ),
                {"schema": schema},
            ).scalar_one()
            is False
        )


def test_postgresql_type_detection_is_schema_scoped(postgres_schema):
    engine, schema = postgres_schema
    with engine.begin() as connection:
        connection.execute(text('CREATE SCHEMA "other_migration_test"'))
        connection.execute(
            text(
                'CREATE TYPE "other_migration_test".paper_matching_run_status AS ENUM '
                "('running', 'completed', 'completed_with_warnings', 'failed')"
            )
        )
    try:
        with _connection(engine, schema) as connection:
            result = migrate_paper_matching_status_enum(connection)
            assert result.converted is True
    finally:
        with engine.begin() as connection:
            connection.execute(text('DROP SCHEMA "other_migration_test" CASCADE'))


def test_postgresql_index_verification_requires_expected_columns(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(text("DROP INDEX uq_matching_active_scope"))
        connection.execute(
            text(
                "CREATE UNIQUE INDEX uq_matching_active_scope "
                "ON paper_matching_runs (scope_key) WHERE status = 'running'"
            )
        )
        with pytest.raises(MatchingStatusEnumMigrationError, match="partial index"):
            migrate_paper_matching_status_enum(connection)


def test_postgresql_index_verification_accepts_normalized_status_predicate(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(text("DROP INDEX uq_matching_active_scope"))
        connection.execute(
            text(
                "CREATE UNIQUE INDEX uq_matching_active_scope "
                "ON paper_matching_runs (trade_date, scope_key) "
                "WHERE (status::text = 'running'::text)"
            )
        )

        result = migrate_paper_matching_status_enum(connection, dry_run=True)

    assert result.index_verified is True


def test_postgresql_enum_rejects_invalid_insert_and_enforces_active_index(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        migrate_paper_matching_status_enum(connection)
        savepoint = connection.begin_nested()
        try:
            with pytest.raises(Exception):
                connection.execute(
                    text(
                        "INSERT INTO paper_matching_runs (trade_date, scope_key, status) "
                        "VALUES ('2026-07-31', 'bad', 'invalid')"
                    )
                )
        finally:
            savepoint.rollback()
        connection.execute(
            text(
                "INSERT INTO paper_matching_runs (trade_date, scope_key, status) "
                "VALUES ('2026-07-31', 'all', 'running')"
            )
        )
        savepoint = connection.begin_nested()
        try:
            with pytest.raises(Exception):
                connection.execute(
                    text(
                        "INSERT INTO paper_matching_runs (trade_date, scope_key, status) "
                        "VALUES ('2026-07-31', 'all', 'running')"
                    )
                )
        finally:
            savepoint.rollback()
