from __future__ import annotations

import os
from datetime import date

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection

from paper_trading.storage.matching_status_migration import (
    MatchingStatusEnumMigrationError,
    migrate_paper_matching_status_enum,
)

LABELS = ("running", "completed", "completed_with_warnings", "failed")


def test_sqlite_dry_run_does_not_execute_postgresql_ddl():
    engine = create_engine("sqlite://")
    with engine.begin() as connection:
        result = migrate_paper_matching_status_enum(connection, dry_run=True)

    assert result.dry_run is True
    assert result.labels == LABELS
    assert result.converted is False
    assert result.index_verified is False


def postgres_engine():
    url = os.getenv("TEST_POSTGRESQL_URL")
    if not url:
        pytest.skip("TEST_POSTGRESQL_URL is unavailable")
    return create_engine(url)


@pytest.fixture()
def postgres_schema():
    engine = postgres_engine()
    schema = "migration_test"
    with engine.begin() as connection:
        connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        connection.execute(text(f'SET search_path TO "{schema}"'))
        connection.execute(
            text(
                """
                CREATE TABLE paper_matching_runs (
                    id integer generated by default as identity primary key,
                    trade_date date not null,
                    scope_key varchar(40) not null,
                    status varchar(32) not null
                )
                """
            )
        )
        connection.execute(
            text(
                "CREATE UNIQUE INDEX uq_matching_active_scope "
                "ON paper_matching_runs (trade_date, scope_key) WHERE status = 'running'"
            )
        )
    yield engine, schema
    with engine.begin() as connection:
        connection.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
    engine.dispose()


def _connection(engine, schema) -> Connection:
    connection = engine.connect()
    connection.execute(text(f'SET search_path TO "{schema}"'))
    return connection


def test_postgresql_rejects_unknown_legacy_status_without_changes(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(
            text("INSERT INTO paper_matching_runs (trade_date, scope_key, status) VALUES (:date, 'all', 'unknown')"),
            {"date": date(2026, 7, 31)},
        )
        with pytest.raises(MatchingStatusEnumMigrationError):
            migrate_paper_matching_status_enum(connection)
        assert connection.execute(text("SELECT status FROM paper_matching_runs")).scalar_one() == "unknown"


def test_postgresql_converts_labels_and_verifies_active_partial_index(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        for status in LABELS:
            connection.execute(
                text("INSERT INTO paper_matching_runs (trade_date, scope_key, status) VALUES (:date, :scope, :status)"),
                {"date": date(2026, 7, 31), "scope": status, "status": status},
            )
        result = migrate_paper_matching_status_enum(connection)

        assert result.converted is True
        assert result.labels == LABELS
        assert result.index_verified is True
        assert (
            connection.execute(
                text("SELECT typname FROM pg_type WHERE typname = 'paper_matching_run_status'")
            ).scalar_one()
            == "paper_matching_run_status"
        )
        assert connection.execute(
            text(
                "SELECT enumlabel FROM pg_enum JOIN pg_type ON pg_type.oid = pg_enum.enumtypid "
                "WHERE pg_type.typname = 'paper_matching_run_status' ORDER BY enumsortorder"
            )
        ).all() == [(label,) for label in LABELS]
        assert (
            connection.execute(
                text(
                    "SELECT pg_get_expr(indpred, indrelid) FROM pg_index "
                    "JOIN pg_class ON pg_class.oid = pg_index.indexrelid "
                    "JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace "
                    "WHERE pg_namespace.nspname = :schema "
                    "AND pg_class.relname = 'uq_matching_active_scope'"
                ),
                {"schema": schema},
            )
            .scalar_one()
            .lower()
            .find("running")
            >= 0
        )


def test_postgresql_migration_is_idempotent(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        first = migrate_paper_matching_status_enum(connection)
        second = migrate_paper_matching_status_enum(connection)

    assert first.converted is True
    assert second.converted is False
    assert second.labels == LABELS
    assert second.index_verified is True


def test_postgresql_dry_run_reports_preflight_facts_without_ddl(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        result = migrate_paper_matching_status_enum(connection, dry_run=True)

        assert result.dry_run is True
        assert result.converted is True
        assert result.labels == ()
        assert result.index_verified is True
        assert (
            connection.execute(
                text(
                    "SELECT EXISTS ("
                    "SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
                    "WHERE n.nspname = :schema AND t.typname = 'paper_matching_run_status'"
                    ")"
                ),
                {"schema": schema},
            ).scalar_one()
            is False
        )


def test_postgresql_type_detection_is_schema_scoped(postgres_schema):
    engine, schema = postgres_schema
    with engine.begin() as connection:
        connection.execute(text('CREATE SCHEMA "other_migration_test"'))
        connection.execute(
            text(
                'CREATE TYPE "other_migration_test".paper_matching_run_status AS ENUM '
                "('running', 'completed', 'completed_with_warnings', 'failed')"
            )
        )
    try:
        with _connection(engine, schema) as connection:
            result = migrate_paper_matching_status_enum(connection)
            assert result.converted is True
    finally:
        with engine.begin() as connection:
            connection.execute(text('DROP SCHEMA "other_migration_test" CASCADE'))


def test_postgresql_index_verification_requires_expected_columns(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(text("DROP INDEX uq_matching_active_scope"))
        connection.execute(
            text(
                "CREATE UNIQUE INDEX uq_matching_active_scope "
                "ON paper_matching_runs (scope_key) WHERE status = 'running'"
            )
        )
        with pytest.raises(MatchingStatusEnumMigrationError, match="partial index"):
            migrate_paper_matching_status_enum(connection)


def test_postgresql_index_verification_accepts_normalized_status_predicate(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        connection.execute(text("DROP INDEX uq_matching_active_scope"))
        connection.execute(
            text(
                "CREATE UNIQUE INDEX uq_matching_active_scope "
                "ON paper_matching_runs (trade_date, scope_key) "
                "WHERE (status::text = 'running'::text)"
            )
        )

        result = migrate_paper_matching_status_enum(connection, dry_run=True)

    assert result.index_verified is True


def test_postgresql_enum_rejects_invalid_insert_and_enforces_active_index(postgres_schema):
    engine, schema = postgres_schema
    with _connection(engine, schema) as connection:
        migrate_paper_matching_status_enum(connection)
        with connection.begin_nested():
            with pytest.raises(Exception):
                connection.execute(
                    text(
                        "INSERT INTO paper_matching_runs (trade_date, scope_key, status) "
                        "VALUES ('2026-07-31', 'bad', 'invalid')"
                    )
                )
        connection.execute(
            text(
                "INSERT INTO paper_matching_runs (trade_date, scope_key, status) "
                "VALUES ('2026-07-31', 'all', 'running')"
            )
        )
        with connection.begin_nested():
            with pytest.raises(Exception):
                connection.execute(
                    text(
                        "INSERT INTO paper_matching_runs (trade_date, scope_key, status) "
                        "VALUES ('2026-07-31', 'all', 'running')"
                    )
                )
